# Independent hand-built-MME anchor for the Henderson MME solver, on a SMALL
# REAL pedigree WITH relatedness.
#
# Issues #1/#2 (close the circularity): the pedigree-based supplied-variance
# fixture (hs_mrode_supplied_variance_validation_fixture in
# R/validation-fixtures.R) pins fixed effects and EBVs that are regenerated by
# the SAME package solver, hs_solve_henderson_mme_reference(). The pinning test
# (test-validation-fixtures.R, "Mrode-style supplied-variance fixture pins R
# reference outputs") therefore compares the solver to numbers the solver itself
# produced: a wrong solver would still pass. The only INDEPENDENT hand-built-MME
# anchor (test-pev-reliability-anchor.R) covers just the tiny diag(3),
# intercept-only toy design (Ainv = identity, no relatedness, single fixed
# column), so it cannot catch errors that only surface with off-diagonal Ainv
# entries or a multi-column X.
#
# This file closes that gap. On the twelve-animal Mrode-style pedigree (which has
# genuine relatedness: Ainv has nonzero off-diagonals tying parents to offspring
# and full sibs) and the fixture's supplied sigma_a2 / sigma_e2, we build the
# mixed-model-equation coefficient matrix and right-hand side BY HAND in lambda
# form,
#
#   lambda = sigma_e2 / sigma_a2
#   C   = [[ X^T X ,        X^T Z          ],
#          [ Z^T X , Z^T Z + Ainv * lambda ]]
#   rhs = [ X^T y ; Z^T y ]
#
# solve(C, rhs), and split the solution into the fixed-effect block (first
# ncol(X) entries) and the animal/EBV block (the rest). We then assert that the
# package solver's fixed_effects and breeding_values match THIS independent hand
# solve to 1e-8. We do NOT call hs_solve_henderson_mme_reference() to produce the
# expected values -- that is exactly the circularity being closed; it is only the
# object under test.
#
# The lambda-form MME is the standard textbook (Henderson / Mrode) parameter
# isation. The package solver builds the algebraically identical precision-scaled
# system -- blocks (1/sigma_e2) * X^T X, etc., with animal block
# (1/sigma_e2) * Z^T Z + (1/sigma_a2) * Ainv -- and rhs (1/sigma_e2) * [X^T y;
# Z^T y]. Multiplying both C and rhs by the constant 1/sigma_e2 leaves
# solve(C, rhs) unchanged, so the two forms have the same solution; the lambda
# form is the independent hand check.
#
# X / Z / y / ids come from hs_build_model_spec() + hs_build_bridge_payload() on
# the fixture's formula/data. Those are payload builders, not the solver under
# test, so reusing them does not reintroduce the circularity. Ainv is the
# hand-built tabular numerator-relationship inverse stored in
# fixture$expected$Ainv (an external check matched it to ~1e-16), not a value the
# solver computed.
#
# NOTE: this anchor proves the package solver agrees with an INDEPENDENT hand
# solve of the SAME MME on this pedigree. The complementary check -- pinning the
# package solver against the PUBLISHED Mrode Example 3.1 textbook EBV constants
# (Mrode 2014, "Linear Models for the Prediction of Animal Breeding Values",
# 3rd ed., p.39) -- now lives in test-mrode-published-anchor.R, using inputs and
# solutions confirmed against three independent citable sources (see
# hs_mrode_example_3_1_fixture()). Together they close both the self-generated-
# number circularity (here) and the external-canon gap (there).
#
# All checks are pure R, fast, CI-runnable: no Julia engine, no skip guards.

test_that("Henderson MME solver matches an independent hand-built MME on a real pedigree (1e-8)", {
  fixture <- hsquared:::hs_mrode_supplied_variance_validation_fixture()
  spec <- hsquared:::hs_build_model_spec(
    fixture$formula,
    data = fixture$data,
    family = stats::gaussian(),
    REML = TRUE
  )
  payload <- hsquared:::hs_build_bridge_payload(spec)

  X <- as.matrix(payload$X)
  Z <- as.matrix(payload$Z)
  y <- payload$y
  ids <- payload$ids
  Ainv <- fixture$expected$Ainv
  sigma_a2 <- fixture$sigma_a2
  sigma_e2 <- fixture$sigma_e2

  # Confirm this really is the twelve-animal design WITH relatedness that the
  # hand build below targets: 12 records, a two-column X (intercept + x), an
  # identity record-incidence Z, a symmetric 12x12 Ainv, and -- the point of
  # this anchor -- genuine off-diagonal Ainv entries (the diag(3) toy in
  # test-pev-reliability-anchor.R has none).
  expect_equal(dim(X), c(12L, 2L))
  expect_equal(as.numeric(X[, 1]), rep(1, 12))
  expect_equal(as.numeric(X[, 2]), fixture$data$x)
  expect_equal(unname(Z), diag(12))
  expect_equal(dim(Ainv), c(12L, 12L))
  expect_equal(Ainv, t(Ainv))
  expect_equal(ids, fixture$expected$ids)
  expect_true(any(Ainv[lower.tri(Ainv)] != 0))

  # --- Hand-built MME (lambda form), solved independently ---------------------
  #   lambda = sigma_e2 / sigma_a2
  #   C   = [[ X^T X ,        X^T Z          ],
  #          [ Z^T X , Z^T Z + Ainv * lambda ]]
  #   rhs = [ X^T y ; Z^T y ]
  lambda <- sigma_e2 / sigma_a2
  C <- rbind(
    cbind(crossprod(X), crossprod(X, Z)),
    cbind(crossprod(Z, X), crossprod(Z) + Ainv * lambda)
  )
  rhs <- c(crossprod(X, y), crossprod(Z, y))
  solution <- solve(C, rhs)

  n_fixed <- ncol(X)
  fixef_anchor <- solution[seq_len(n_fixed)]
  ebv_anchor <- solution[-seq_len(n_fixed)]

  # --- Object under test ------------------------------------------------------
  # Produced by the package solver; its expected values are NOT used to build the
  # anchor above (that is the circularity being closed).
  reference <- hsquared:::hs_solve_henderson_mme_reference(
    y = y,
    X = X,
    Z = Z,
    Ainv = Ainv,
    sigma_a2 = sigma_a2,
    sigma_e2 = sigma_e2,
    ids = ids
  )

  # The solver must match the INDEPENDENT hand solve, not a value it produced.
  expect_equal(
    unname(reference$fixed_effects),
    unname(fixef_anchor),
    tolerance = 1e-8
  )
  expect_equal(
    reference$breeding_values$value,
    unname(ebv_anchor),
    tolerance = 1e-8
  )
  # EBVs stay aligned to the pedigree IDs.
  expect_equal(reference$breeding_values$id, ids)
})

test_that("pedigree MME anchor rejects perturbed solver outputs (test of test)", {
  fixture <- hsquared:::hs_mrode_supplied_variance_validation_fixture()
  spec <- hsquared:::hs_build_model_spec(
    fixture$formula,
    data = fixture$data,
    family = stats::gaussian(),
    REML = TRUE
  )
  payload <- hsquared:::hs_build_bridge_payload(spec)

  X <- as.matrix(payload$X)
  Z <- as.matrix(payload$Z)
  y <- payload$y
  ids <- payload$ids
  Ainv <- fixture$expected$Ainv
  sigma_a2 <- fixture$sigma_a2
  sigma_e2 <- fixture$sigma_e2

  # Same hand build as above.
  lambda <- sigma_e2 / sigma_a2
  C <- rbind(
    cbind(crossprod(X), crossprod(X, Z)),
    cbind(crossprod(Z, X), crossprod(Z) + Ainv * lambda)
  )
  rhs <- c(crossprod(X, y), crossprod(Z, y))
  solution <- solve(C, rhs)
  n_fixed <- ncol(X)
  ebv_anchor <- solution[-seq_len(n_fixed)]

  reference <- hsquared:::hs_solve_henderson_mme_reference(
    y = y,
    X = X,
    Z = Z,
    Ainv = Ainv,
    sigma_a2 = sigma_a2,
    sigma_e2 = sigma_e2,
    ids = ids
  )

  # Sanity: the solver still matches the genuine anchor at the real tolerance, so
  # the rejection below is of a deliberately wrong value, not a broken anchor.
  expect_equal(
    reference$breeding_values$value,
    unname(ebv_anchor),
    tolerance = 1e-8
  )

  # Test of test: EBVs perturbed by +0.1 (far beyond 1e-8) must NOT compare
  # equal. If they did, the anchor assertion above would be vacuous -- which is
  # precisely the failure mode of the circular pinning test this file replaces.
  wrong_ebv <- unname(ebv_anchor) + 0.1
  expect_false(isTRUE(all.equal(
    reference$breeding_values$value,
    wrong_ebv,
    tolerance = 1e-8
  )))
  expect_failure(expect_equal(
    reference$breeding_values$value,
    wrong_ebv,
    tolerance = 1e-8
  ))
})
