# Published external-canon anchor: Mrode Example 5.1, as reproduced in the
# LUKE multiple-trait animal-model note and Masuda's BLUPF90 tutorial. This is
# a supplied-G0/R0 BLUP/MME target, not variance-component estimation.

test_that("the multivariate Henderson MME solver reproduces Mrode Example 5.1 solutions", {
  fixture <- hsquared:::hs_mrode_example_5_1_multitrait_fixture()

  reference <- hsquared:::hs_solve_multivariate_henderson_mme_reference(
    Y = as.matrix(fixture$data[, fixture$traits]),
    sex = fixture$data$sex,
    animal = fixture$data$animal,
    ids = fixture$ids,
    Ainv = fixture$expected$Ainv,
    G0 = fixture$G0,
    R0 = fixture$R0,
    traits = fixture$traits
  )

  # Load-bearing: these match the published printed fixed effects from the
  # Mrode Example 5.1 reproduction, not values generated by this test.
  expect_equal(
    reference$fixed_effects,
    fixture$expected$fixed_effects,
    tolerance = 5e-5
  )

  expected <- fixture$expected$breeding_values
  observed <- reference$breeding_values
  expect_equal(observed$id, expected$id)
  expect_equal(observed$trait, expected$trait)

  # Animal BLUPs are printed to five significant decimals in the source. The
  # tolerance is therefore intentionally at the published-digit scale.
  expect_equal(observed$value, expected$value, tolerance = 5e-5)
})

test_that("the multivariate Mrode anchor rejects perturbed animal BLUPs", {
  fixture <- hsquared:::hs_mrode_example_5_1_multitrait_fixture()

  reference <- hsquared:::hs_solve_multivariate_henderson_mme_reference(
    Y = as.matrix(fixture$data[, fixture$traits]),
    sex = fixture$data$sex,
    animal = fixture$data$animal,
    ids = fixture$ids,
    Ainv = fixture$expected$Ainv,
    G0 = fixture$G0,
    R0 = fixture$R0,
    traits = fixture$traits
  )
  published <- fixture$expected$breeding_values$value

  expect_equal(reference$breeding_values$value, published, tolerance = 5e-5)
  expect_failure(expect_equal(
    reference$breeding_values$value,
    published + 0.01,
    tolerance = 5e-5
  ))
})
