# Independent anchor for the PEV / reliability reference functions.
#
# Issue #10: hs_henderson_pev_reference() and hs_henderson_reliability_reference()
# (R/validation-fixtures.R) are exercised in CI only against machine-literal
# expectations generated by the SAME formula. That is a tautology: the reference
# is compared to numbers the reference itself produced, so a wrong formula would
# still pass. There is no INDEPENDENT anchor and no negative control.
#
# These tests close that gap. For a tiny supplied-variance animal model we build
# the mixed-model-equation (MME) coefficient matrix BY HAND in lambda form,
#
#   lambda = sigma_e2 / sigma_a2
#   C = [[ X^T X ,        X^T Z          ],
#        [ Z^T X , Z^T Z + Ainv * lambda ]]
#
# invert it, and read prediction error variance (PEV) for each animal from the
# diagonal of the animal block of  solve(C) * sigma_e2 . Reliability is then
#   r2 = 1 - PEV / (sigma_a2 * diag(A)) ,  with A = solve(Ainv).
#
# Why solve(C) * sigma_e2 gives PEV. The package reference solves the
# precision-scaled MME with blocks (1/sigma_e2) * X^T X, etc., and the animal
# block (1/sigma_e2) * Z^T Z + (1/sigma_a2) * Ainv. That precision-scaled matrix
# equals C / sigma_e2 (factor out 1/sigma_e2; note (1/sigma_a2)*Ainv =
# (1/sigma_e2)*lambda*Ainv). Hence its inverse equals solve(C) * sigma_e2, and
# the animal-block diagonal of that inverse is the PEV. We derive the expected
# values from this hand build and do NOT call the package reference to compute
# them. The reference is only the object under test.
#
# All checks are pure R, fast, CI-runnable: no Julia engine, no skip guards.

# Tiny design: 3 founders, intercept-only, Ainv = diag(3), sigma_a2 = sigma_e2 = 1.
# This is the package's `tiny_sparse_reml_likelihood_identity` fixture
# (hs_reml_likelihood_validation_fixture in R/validation-fixtures.R), so the
# anchor also confirms the hand build is consistent with that exact fixture.

test_that("PEV/reliability reference matches an independently hand-built MME (1e-8)", {
  fixture <- hsquared:::hs_reml_likelihood_validation_fixture()
  spec <- hsquared:::hs_build_model_spec(
    fixture$formula,
    data = fixture$data,
    family = stats::gaussian(),
    REML = TRUE
  )
  payload <- hsquared:::hs_build_bridge_payload(spec)

  X <- as.matrix(payload$X)
  Z <- as.matrix(payload$Z)
  Ainv <- fixture$expected$Ainv
  sigma_a2 <- fixture$sigma_a2
  sigma_e2 <- fixture$sigma_e2

  # Confirm the fixture really is the tiny intercept-only diag(3) design this
  # anchor is written for, so the hand build below stays faithful. Compare bare
  # numeric content (model.matrix carries an `assign` attribute on X).
  expect_equal(dim(X), c(3L, 1L))
  expect_equal(as.numeric(X), rep(1, 3))
  expect_equal(unname(as.matrix(Z)), diag(3))
  expect_equal(Ainv, diag(3))
  expect_equal(sigma_a2, 1)
  expect_equal(sigma_e2, 1)

  # --- Hand-built MME coefficient matrix C (lambda form) ----------------------
  #   C = [[ X^T X ,        X^T Z          ],
  #        [ Z^T X , Z^T Z + Ainv * lambda ]]
  lambda <- sigma_e2 / sigma_a2
  C <- rbind(
    cbind(crossprod(X), crossprod(X, Z)),
    cbind(crossprod(Z, X), crossprod(Z) + Ainv * lambda)
  )
  C_inv <- solve(C)

  # PEV from the animal block of solve(C) * sigma_e2 (see header derivation).
  n_fixed <- ncol(X)
  animal_block <- C_inv[
    -seq_len(n_fixed),
    -seq_len(n_fixed),
    drop = FALSE
  ]
  pev_anchor <- diag(animal_block) * sigma_e2

  # Reliability: r2 = 1 - PEV / (sigma_a2 * diag(A)), A = solve(Ainv).
  A <- solve(Ainv)
  reliability_anchor <- 1 - pev_anchor / (sigma_a2 * diag(A))

  # --- Object under test ------------------------------------------------------
  pev_ref <- hsquared:::hs_henderson_pev_reference(
    X,
    Z,
    Ainv,
    sigma_a2,
    sigma_e2
  )
  reliability_ref <- hsquared:::hs_henderson_reliability_reference(
    X,
    Z,
    Ainv,
    sigma_a2,
    sigma_e2
  )

  # The reference must match the INDEPENDENT hand build, not a value it produced.
  expect_equal(unname(pev_ref), unname(pev_anchor), tolerance = 1e-8)
  expect_equal(
    unname(reliability_ref),
    unname(reliability_anchor),
    tolerance = 1e-8
  )
})

test_that("PEV/reliability anchor rejects perturbed expected values (test of test)", {
  fixture <- hsquared:::hs_reml_likelihood_validation_fixture()
  spec <- hsquared:::hs_build_model_spec(
    fixture$formula,
    data = fixture$data,
    family = stats::gaussian(),
    REML = TRUE
  )
  payload <- hsquared:::hs_build_bridge_payload(spec)

  X <- as.matrix(payload$X)
  Z <- as.matrix(payload$Z)
  Ainv <- fixture$expected$Ainv
  sigma_a2 <- fixture$sigma_a2
  sigma_e2 <- fixture$sigma_e2

  # Same hand build as above.
  lambda <- sigma_e2 / sigma_a2
  C <- rbind(
    cbind(crossprod(X), crossprod(X, Z)),
    cbind(crossprod(Z, X), crossprod(Z) + Ainv * lambda)
  )
  C_inv <- solve(C)
  n_fixed <- ncol(X)
  pev_anchor <- diag(
    C_inv[-seq_len(n_fixed), -seq_len(n_fixed), drop = FALSE]
  ) *
    sigma_e2
  A <- solve(Ainv)
  reliability_anchor <- 1 - pev_anchor / (sigma_a2 * diag(A))

  reliability_ref <- unname(
    hsquared:::hs_henderson_reliability_reference(
      X,
      Z,
      Ainv,
      sigma_a2,
      sigma_e2
    )
  )

  # Sanity: the reference still matches the genuine anchor at the real tolerance,
  # so the rejection below is of a deliberately wrong value, not a broken anchor.
  expect_equal(reliability_ref, unname(reliability_anchor), tolerance = 1e-8)

  # Test of test: reliability perturbed by +0.1 (far beyond 1e-8) must NOT
  # compare equal. If it did, the anchor assertion above would be vacuous.
  wrong_reliability <- unname(reliability_anchor) + 0.1
  expect_false(isTRUE(all.equal(
    reliability_ref,
    wrong_reliability,
    tolerance = 1e-8
  )))

  # The discriminating comparison is also detectable through testthat's own
  # failure machinery, not just all.equal().
  expect_failure(expect_equal(
    reliability_ref,
    wrong_reliability,
    tolerance = 1e-8
  ))
})
